/*
 * This source file was generated by the Gradle 'init' task
 */
package me.eeshe.tempus;

import com.googlecode.lanterna.terminal.DefaultTerminalFactory;

import me.eeshe.tempus.ui.TimeTrackerScreen;

public class Tempus {
  public static void main(String[] args) {
    DefaultTerminalFactory terminalFactory = new DefaultTerminalFactory();
    new TimeTrackerScreen().open(terminalFactory);
  }
}
