spring.application.name=tempus

spring.session.jdbc.initialize-schema=always
spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-sqlite.sql
spring.session.timeout=30d

spring.datasource.url=jdbc:sqlite:data/database.db
spring.datasource.hikari.maximum-pool-size=1

spring.jpa.hibernate.ddl-auto=update

server.tomcat.max-part-count=200
